# Generated by Django 5.1.2 on 2024-10-30 07:52

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
