# Generated by Django 5.1.2 on 2024-11-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Cart's Item",
                "verbose_name_plural": "Cart's Items",
            },
        ),
    ]
