# Generated by Django 5.1.2 on 2024-11-06 20:17

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_account_type_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country_en",
            field=django_countries.fields.CountryField(
                max_length=2, null=True, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country_ka",
            field=django_countries.fields.CountryField(
                max_length=2, null=True, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer Not To Say"),
                ],
                default="P",
                max_length=2,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender_en",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer Not To Say"),
                ],
                default="P",
                max_length=2,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender_ka",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer Not To Say"),
                ],
                default="P",
                max_length=2,
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
