# Generated by Django 5.1.2 on 2024-11-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_alter_customuser_country_alter_customuser_country_en_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="account_type_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="account_type_ka",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city_ka",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="country_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="country_ka",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="gender_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="gender_ka",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="street_address_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="street_address_ka",
        ),
    ]
