# Generated by Django 5.1.2 on 2024-10-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tea",
            name="contains_caffeine",
            field=models.BooleanField(default=True),
        ),
    ]
