# Generated by Django 5.1.2 on 2024-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_tea_contains_caffeine"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True, null=True),
        ),
        migrations.AddField(
            model_name="tea",
            name="slug",
            field=models.SlugField(unique=True, null=True),
        ),
    ]
