# Generated by Django 5.1.2 on 2024-10-20 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_auto_20241020_1652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="tea",
            name="slug",
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
