# Generated by Django 5.1.2 on 2024-10-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_tea_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Product Tag",
                "verbose_name_plural": "Product Tags",
            },
        ),
        migrations.AddField(
            model_name="tea",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="teas", to="store.tag"
            ),
        ),
    ]
