# Generated by Django 5.1.2 on 2024-11-06 05:51

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_tag_tea_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tea",
            options={
                "ordering": ("name",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="category name"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="product tag name"
            ),
        ),
        migrations.AlterField(
            model_name="tea",
            name="contains_caffeine",
            field=models.BooleanField(
                default=True, verbose_name="does product contain caffeine"
            ),
        ),
        migrations.AlterField(
            model_name="tea",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="products/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="tea",
            name="manufacturer",
            field=models.CharField(max_length=100, verbose_name="product manufacturer"),
        ),
        migrations.AlterField(
            model_name="tea",
            name="name",
            field=models.CharField(max_length=255, verbose_name="product name"),
        ),
        migrations.AlterField(
            model_name="tea",
            name="place_of_origin",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="place of origin"
            ),
        ),
        migrations.AlterField(
            model_name="tea",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="product price"
            ),
        ),
        migrations.AlterField(
            model_name="tea",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="product stock quantity"
            ),
        ),
    ]
