# Generated by Django 5.1.2 on 2024-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_tea_options_alter_category_name_alter_tag_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="category description"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ka",
            field=models.TextField(
                blank=True, null=True, verbose_name="category description"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="category name"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ka",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="category name"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="product tag name"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ka",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="product tag name"
            ),
        ),
        migrations.AddField(
            model_name="tea",
            name="description_en",
            field=models.TextField(null=True, verbose_name="product description"),
        ),
        migrations.AddField(
            model_name="tea",
            name="description_ka",
            field=models.TextField(null=True, verbose_name="product description"),
        ),
        migrations.AddField(
            model_name="tea",
            name="ingredients_en",
            field=models.TextField(blank=True, null=True, verbose_name="ingredients"),
        ),
        migrations.AddField(
            model_name="tea",
            name="ingredients_ka",
            field=models.TextField(blank=True, null=True, verbose_name="ingredients"),
        ),
        migrations.AddField(
            model_name="tea",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="product name"
            ),
        ),
        migrations.AddField(
            model_name="tea",
            name="name_ka",
            field=models.CharField(
                max_length=255, null=True, verbose_name="product name"
            ),
        ),
        migrations.AddField(
            model_name="tea",
            name="place_of_origin_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="place of origin"
            ),
        ),
        migrations.AddField(
            model_name="tea",
            name="place_of_origin_ka",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="place of origin"
            ),
        ),
    ]
